##spring:
##  cloud:
##    config:
##      server:
##        git:
##          uri: https://github.com/spring-cloud-samples/config-repo
##
#
server:
  port: ${MS_PORT:8888}

management:
  context-path: /

logging:
  level:
    com.netflix.discovery: 'ERROR'
    org.springframework.cloud: 'DEBUG'
    org.springframework.cloud.config.server: 'DEBUG'

spring:
  cloud:
    config:
      enabled: true
      server:
        git:
          # Checkout ourselfs for the sake of the demo
          uri: https://github.com/spring-cloud-samples/config-repo
          #password:
          #username:
          clone-on-start: true
          #basedir: cloud-config/
